farm/farm/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    ('^$', 'cows.views.HomePage'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    ('^cows/$','cows.views.All_Cows'),
    ('^records/$', 'cows.views.All_Records'),
    ('^register/$', 'cows.views.Cow_Registration'),
    ('^cows/(?P<cowslug>.*)/$', 'cows.views.Specific_Cow'),
    ('^breeds/(?P<breedslug>.*)/$', 'cows.views.Specific_Breed'),
    ('^herdbook/(?P<herdbookslug>.*)/$', 'cows.views.Specific_Herd_Book'),
)

farm/cows/models.py
from django.db import models
from django.db.models.signals import post_save

Sex_choices = (('M', 'Male'),('F','Female'),)

class Cow(models.Model):
    ear_tag     = models.CharField(max_length=100)
    reg_name    = models.CharField(max_length=100)
    slug        = models.SlugField(unique=True)
    cow_id      = models.CharField(max_length=100)
    breed       = models.ForeignKey('Breed')
    herd_book   = models.ForeignKey('Herd_Book')
    sex         = models.CharField(max_length=1, choices=Sex_choices)
    grade       = models.CharField(max_length=100)
    birthday    = models.DateField()
    status      = models.TextField(blank=True)
	
    def __unicode__(self):
	   return self.reg_name

       



class Breed(models.Model):
    name        = models.CharField(max_length=100)
    slug        = models.SlugField(unique=True)
    description = models.TextField(blank=True)
	
    def __unicode__(self):
	   return self.name


class Herd_Book(models.Model):
    name        = models.CharField(max_length=100)
    slug        = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
	   return self.name 

class HealthStatus(models.Model):
    cow         = models.ForeignKey('Cow')
    date        = models.DateField(auto_now=True)
    status      = models.TextField()

class ServiceDate(models.Model):
    cow             = models.ForeignKey('Cow')
    date            = models.DateField()
    description     = models.TextField()

class CalvingDate(models.Model):
    cow             = models.ForeignKey('Cow')
    date            = models.DateField()
    note            = models.TextField(blank=True)                 

farm/cows/forms.py
from django import forms
from django.forms import ModelForm
from cows.models import Cow, Breed, Herd_Book, ServiceDate, CalvingDate, HealthStatus, Sex_choices 


class RegisterCowForm(ModelForm):
    ear_tag     = forms.CharField(label=(u'Ear Tag'))
    reg_name    = forms.CharField(label=(u'Reg Name'))
    cow_id      = forms.CharField(label=(u'ID'))
    breed       = forms.ModelChoiceField(queryset=Breed.objects.all())
    herd_book   = forms.ModelChoiceField(queryset=Herd_Book.objects.all())
    sex         = forms.CharField(max_length=1,widget=forms.Select(choices=Sex_choices))
    grade       = forms.CharField(label=(u'grade'))
    birthday    = forms.DateField()
    status      = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Cow
        exclude = ('herd_book','breed')

    def clean_ear_tag(self):
        ear_tag = self.cleaned_data['ear_tag']
       	try:
       	    Cow.objects.get(ear_tag=ear_tag)
       	except Cow.DoesNotExist:
       	    return ear_tag
       	raise forms.ValidationError("Sorry,that ear_tag has already being registered in the database.")

    

farm/cows/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template  import RequestContext
from cows.models import Cow, Breed, Herd_Book, ServiceDate, CalvingDate, HealthStatus 
from cows.forms import RegisterCowForm



def All_Cows(request):
    cows        = Cow.objects.all().order_by('cow_id')
    context     = {'cows':cows}
    return render_to_response('allcows.html',context,context_instance=RequestContext(request)) 


def Specific_Cow(request, cowslug):
    cow             = Cow.objects.get(slug=cowslug)
    health_status   = HealthStatus.objects.all().filter(cow=cow).order_by('-date')
    service_dates   = ServiceDate.objects.all().filter(cow=cow).order_by('-date')
    calving_dates    = CalvingDate.objects.all().filter(cow=cow).order_by('-date')
    context         = {'cow': cow, 'health_status':health_status, 'service_dates':service_dates, 'calving_dates':calving_dates}
    return render_to_response('cow.html', context, context_instance=RequestContext(request))


def Specific_Breed(request, breedslug):
    breed       = Breed.objects.get(slug=breedslug)
    cows        = Cow.objects.filter(breed=breed)
    context     = {'cows':cows, 'breed':breed}
    return render_to_response('breed.html', context, context_instance=RequestContext(request))    


def Specific_Herd_Book(request, herdbookslug):
    herd_book    = Herd_Book.objects.get(slug=herdbookslug)
    cows         = Cow.objects.filter(herd_book=herd_book)
    context      = {'cows':cows, 'herd_book':herd_book}
    return render_to_response('herd_book.html', context, context_instance=RequestContext(request))


def Service_Dates(request):
    service_dates =   HealthStatus.objects().order_by('date')
    context = {'service_dates':service_dates}

def All_Records(request):
    cows        = Cow.objects.all().order_by('cow_id')
    health_status   = HealthStatus.objects.all().order_by('-date')
    service_dates   = ServiceDate.objects.all().order_by('-date')
    calving_dates    = CalvingDate.objects.all().order_by('-date')
    breeds       = Breed.objects.all()
    herd_books    = Herd_Book.objects.all()
    context = {'cows': cows, 'health_status':health_status,'breeds':breeds, 'herd_books':herd_books,
                'service_dates':service_dates, 'calving_dates':calving_dates}
    return render_to_response('records.html', context, context_instance=RequestContext(request))
            




def HomePage(request):
    cows        = Cow.objects.all().order_by('ear_tag')
    context     = {'cows':cows}
    return render_to_response('home.html',context,context_instance=RequestContext(request))

def Cow_Registration(request):
    if request.method == 'POST':
        form = RegisterCowForm(request.POST)
        if form.is_valid():
            cow = Cow(ear_tag = form.cleaned_data['ear_tag'],
                                         slug=form.cleaned_data['slug'],   
                                         reg_name = form.cleaned_data['reg_name'], 
                                        cow_id = form.cleaned_data['cow_id'],
                                        breed=form.cleaned_data['breed'],
                                        sex=form.cleaned_data['sex'],
                                        grade=form.cleaned_data['grade'],
                                        herd_book=form.cleaned_data['herd_book'],
                                        birthday=form.cleaned_data['birthday'],
                                        status=form.cleaned_data['status'])
            cow.save()
            return HttpResponseRedirect('/cows/')
        else:
            return render_to_response('register.html', {'form':form}, context_instance=RequestContext(request))        
    else:
        ''' form not being submitted, show them the blank registration form  for submission'''
        form  = RegisterCowForm()
        context = {'form':form}
        return render_to_response('register.html', context, context_instance=RequestContext(request))
                












    

farm/templates/allcows.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Cows
                    <div class="form-group input-group col-lg-6 pull-right">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                    </h1>                    
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            All cows in the Database
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Ear Tag</th>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Reg Name</th>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Sex</th>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Breed</th>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Herd Book</th>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> ID</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	{% for cow in cows %}
                                    	
                                        <tr class="odd gradeX">
                                        	<td><a href="/cows/{{ cow.slug }}/">{{ cow.ear_tag }}</a></td>            
                                            <td><a href="/cows/{{ cow.slug }}/">{{ cow }}</a></td>
                                            <td>{{ cow.get_sex_display }}</td>                                 
                                            <td class="center">{{ cow.breed }}</td>
                                            <td class="center">{{ cow.herd_book }}</td>
                                            <td>{{ cow.cow_id }}</td>
                                        	
                                        </tr>
                                    
                                        {% endfor %}
                                        
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->


{% endblock %}

farm/templates/breed.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static "css/plugins/timeline/timeline.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

	<div id="page-wrapper">
	 	<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ breed }}
                    
                                        <div class="form-group input-group col-lg-6 pull-right">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                    </h1 >                    
                </div>
                <!-- /.col-lg-12 -->
         </div>
	            <div class="row">
	                <div class="col-lg-8">
	                	<div class="panel panel-default">
	                		<div class="panel-heading">
	                			Cows
	                		</div>
		                	<div class="panel-body">
		                	    <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Ear Tag</th>
                                            <th>Reg Name</th>
                                            <th>Sex</th>
                                           
                                            <th>Herd Book</th>
                                            <th>ID</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for cow in cows %}
                                        
                                        <tr class="odd gradeX">
                                            <td><a href="/cows/{{ cow.slug }}/">{{ cow.ear_tag }}</a></td>            
                                            <td><a href="/cows/{{ cow.slug }}/">{{ cow }}</a></td>
                                            <td>{{ cow.get_sex_display }}</td>                                 
                                            <td class="center">{{ cow.herd_book }}</td>
                                            <td>{{ cow.cow_id }}</td>
                                            
                                        </tr>
                                    
                                        {% endfor %}
                                        
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            </div>

							</div>
				
                        
                
				    
                </div>
                <!-- /.col-lg-8 -->


				<div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-picture"></span> Photo
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                          <i class="fa fa-info"></i> Breed Description
                        </div>
                        <div class="panel-body">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan. Aliquam ornare lacus adipiscing, posuere lectus et, fringilla augue.</p>
                        </div>
                        
                    </div>
                    
                

                    
                </div>    
	</div>

{% endblock %}

farm/templates/cow.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static "css/plugins/timeline/timeline.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

	<div id="page-wrapper">
	 	<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ cow }}
                    <span class="fa fa-tags text-muted small">{{ cow.ear_tag }}</span>
                                        <div class="form-group input-group col-lg-6 pull-right">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                    </h1 >                    
                </div>
                <!-- /.col-lg-12 -->
         </div>
	            <div class="row">
	                <div class="col-lg-8">
	                	<div class="panel panel-default">
	                		<div class="panel-heading">
	                			Cow Details
	                		</div>
		                	<div class="panel-body">
		                	    <div class="list-group">

		                			<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-tag"></icon> Tag
	                                    <span class="pull-right text-muted">{{ cow.ear_tag }}
	                                    </span>
                                	</a>
		                			<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-pencil"></icon> Name
	                                    <span class="pull-right text-muted">{{ cow }}
	                                    </span>
                                	</a>
                                	<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-asterisk"></icon> Sex
	                                    <span class="pull-right text-muted">{{ cow.get_sex_display }}
	                                    </span>
                                	</a>
                                	
                                	<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-leaf"></icon> Breed
	                                    <span class="pull-right text-muted">{{ cow.breed }}
	                                    </span>
                                	</a>
                                	
                                	<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-info-sign"></icon> Grade
	                                    <span class="pull-right text-muted">{{ cow.grade }}
	                                    </span>
                                	</a>
                                	<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-book"></icon> Herd Book
	                                    <span class="pull-right text-muted">{{ cow.herd_book }}
	                                    </span>
                                	</a>
                                	<a  class="list-group-item">
	                                    <icon class="glyphicon glyphicon-calendar"></icon> Date Of Birth
	                                    <span class="pull-right text-muted">{{ cow.birthday }}
	                                    </span>
                                	</a>
                                	
                                 </div>       
						

							</div>
						</div>
                        <div class="panel panel-info">
                        <div class="panel-heading">
                            <i class="fa fa-ambulance"></i> Health Status
                        </div>
                        <div class="panel-body">
                            {% for cowstatus in health_status %}
                            <p class="text-muted small">{{ cowstatus.date }}</p>
                            <p>{{ cowstatus.status }}</p>
                            <hr id ="divider"/>
                            {% endfor %}
                        </div>
                       
                    </div>
                
				    
                </div>
                <!-- /.col-lg-8 -->


				<div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-picture"></span> Photo
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                          <i class="fa fa-calendar"></i> Service Dates
                        </div>
                        <div class="panel-body">
                            {% for cow_service in service_dates %}
                            <p class="text-muted small">{{ cow_service.date }}</p>
                            <p class="small">{{ cow_service.description }}</p>
                            <hr id ="divider"/>
                            {% endfor %}
                        </div>
                        
                    </div>
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <i class="fa fa-calendar"></i> Calving Dates
                        </div>
                        <div class="panel-body">
                            {% for cow_calving in calving_dates %}
                            <p class="text-muted small">{{ cow_calving.date }}</p>
                            <p>{{ cow_calving.note }}</p>
                            <hr id ="divider"/>
                            {% endfor %}
                        </div>
                        
                    </div>
                

                    
                </div>    
	</div>

{% endblock %}

farm/templates/herd_book.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static "css/plugins/timeline/timeline.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

	<div id="page-wrapper">
	 	<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ herd_book }}
                    
                                        <div class="form-group input-group col-lg-6 pull-right">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                    </h1 >                    
                </div>
                <!-- /.col-lg-12 -->
         </div>
	            <div class="row">
	                <div class="col-lg-8">
	                	<div class="panel panel-default">
	                		<div class="panel-heading">
	                			Cows
	                		</div>
		                	<div class="panel-body">
		                	    <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th><icon class="glyphicon glyphicon-tag"></icon> Ear Tag</th>
                                            <th>Reg Name</th>
                                            <th>Sex</th>
                                            <th>Breed</th>
                                            <th>ID</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for cow in cows %}
                                        
                                        <tr class="odd gradeX">
                                            <td><a href="/cows/{{ cow.slug }}/">{{ cow.ear_tag }}</a></td>            
                                            <td><a href="/cows/{{ cow.slug }}/">{{ cow }}</a></td>
                                            <td>{{ cow.get_sex_display }}</td>                                 
                                            <td class="center">{{ cow.breed }}</td>
                                            <td>{{ cow.cow_id }}</td>
                                            
                                        </tr>
                                    
                                        {% endfor %}
                                        
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            </div>

							</div>
				
                        
                
				    
                </div>
                <!-- /.col-lg-8 -->


				<div class="col-lg-4">
                    
                    <div class="panel panel-info">
                        <div class="panel-heading">
                          <i class="fa fa-info"></i> Herd Description
                        </div>
                        <div class="panel-body">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan. Aliquam ornare lacus adipiscing, posuere lectus et, fringilla augue.</p>
                        </div>
                        
                    </div>
                    
                

                    
                </div>    
	</div>

{% endblock %}

farm/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="DAiry Farm Record system - Web interface ">
    <meta name="author" content="Eric Ndung'u">

    <title>Landing Page Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}"rel="stylesheet">
   

    <!-- Add custom CSS here -->
    <link href="{% static "css/landing-page.css" %}" rel="stylesheet">

</head>

<body>
    <div id="body">

    
    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <div class="intro-message">
                        <h1>Dr.Wamukuru's Dairy Farm<h1>
                             <hr class="intro-divider">
                        <h3>Dairy Cows Records System</h3>
                        <hr class="intro-divider">
                        </h2>

                            <div class="form-group input-group col-lg-4 col-lg-offset-4">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                        </h2>

                        
                       
                        <ul class="list-inline intro-social-buttons">
                            
                            <li><a class="btn btn-default btn-lg"><i class="glyphicon glyphicon-log-in fa-fw"></i> <span class="network-name">Login</span></a>
                            </li>
                            <li><a href="/records" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-stats fa-fw"></i> <span class="network-name">View Records</span></a>
                            </li>
                        </ul>
                    

                    </div>
                    
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
    <footer>
        <p class="small">Copyright &copy; 2014. All Rights Reserved</p>
        <p class="small"> Developed by Eric Ndung'u</p> 
        <p class="small"><i class="fa fa-envelope"></i>   ericobain@gmail.com</p>
    </footer>

    

 
        
    

    <!-- JavaScript -->
    <script src="{% static "js/jquery-1.10.2.js" %}"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
</div>
</body>

</html>